package com.djwilde.inzynierka.config;

import java.util.*;

public class GnuplotConstants {
    public static final String[] GNUPLOT_KEYWORDS = new String[] {
            "break", "cd", "call", "clear", "continue", "do", "evaluate", "exit", "fit", "help", "history", "if", "for",
            "import", "load", "pause", "plot", "print", "printerr", "pwd", "quit", "raise", "refresh", "replot", "reread",
            "reset", "save", "set", "shell", "splot", "stats", "system", "test", "toggle", "undefine", "unset", "update",
            "while"
    };

    public static Map<String, List<String>> GNUPLOT_COMMANDS_AND_ARGUMENTS;
    public static Map<String, List<String>> GNUPLOT_COMMANDS_AND_KEYWORDS;
    public static Map<String, List<String>> GNUPLOT_COMMANDS_AND_TEMPLATES;

    static {
        Map<String, List<String>> commandsAndArguments = new LinkedHashMap<>();
        Map<String, List<String>> commandsAndKeywords = new LinkedHashMap<>();
        Map<String, List<String>> commandsAndTemplates = new LinkedHashMap<>();

        commandsAndArguments.put("break", null);
        commandsAndArguments.put("cd", List.of("directoryName"));
        commandsAndArguments.put("call", List.of("inputFile", "param1","param2","param3","param4","param5","param6","param7",
                "param8","param9"));
        commandsAndArguments.put("clear", null);
        commandsAndArguments.put("continue", null);
        commandsAndArguments.put("do", null);
        commandsAndArguments.put("eval", List.of("expression"));
        commandsAndArguments.put("exit", null);
        commandsAndArguments.put("exit message", List.of("message"));
        commandsAndArguments.put("exit status", List.of("errorCode"));
        commandsAndArguments.put("for", List.of("intvar", "stringvar"));
        commandsAndArguments.put("fit", List.of("ranges", "expression", "datafile", "datafileModifiers", "unitweights", "parameterFile", "var1"));
        commandsAndArguments.put("help", List.of("topic"));
        commandsAndArguments.put("history", List.of("lastNEntries", "file", "expression"));
        commandsAndArguments.put("if", List.of("condition"));
        commandsAndArguments.put("import", List.of("func", "sharedObj", "sharedSymbol"));
        commandsAndArguments.put("load", List.of("inputFile"));
        commandsAndArguments.put("lower", List.of("plotWindowId"));
        commandsAndArguments.put("pause", List.of("time", "string"));
        commandsAndArguments.put("pause mouse", List.of("endCondition", "string"));
        commandsAndArguments.put("pause mouse close", null);
        commandsAndArguments.put("plot", List.of("ranges", "plotElement"));
        commandsAndArguments.put("print", List.of("expression"));
        commandsAndArguments.put("printerr", List.of("expression"));
        commandsAndArguments.put("pwd", null);
        commandsAndArguments.put("quit", null);
        commandsAndArguments.put("raise", List.of("plotWindowId"));
        commandsAndArguments.put("refresh", null);
        commandsAndArguments.put("replot", null);
        commandsAndArguments.put("reread", null);
        commandsAndArguments.put("reset", null);
        commandsAndArguments.put("reset session", null);
        commandsAndArguments.put("reset errors", null);
        commandsAndArguments.put("reset bind", null);
        commandsAndArguments.put("save", List.of("filename"));
        commandsAndArguments.put("save functions", List.of("filename"));
        commandsAndArguments.put("save variables", List.of("filename"));
        commandsAndArguments.put("save terminal", List.of("filename"));
        commandsAndArguments.put("save set", List.of("filename"));
        commandsAndArguments.put("save fit", List.of("filename"));
        commandsAndArguments.put("set angles", null);
        commandsAndArguments.put("set arrow", List.of("position1", "position2", "coord", "ang", "arrow_style", "headlength",
                "headangle", "linestyle", "linetype", "linewidth", "colorspec", "dashtype", "type"));
        commandsAndArguments.put("set autoscale", List.of("axes"));
        commandsAndArguments.put("set autoscale noextend", null);
        commandsAndArguments.put("set autoscale keepfix", null);
        commandsAndArguments.put("set bmargin", List.of("margin"));
        commandsAndArguments.put("set lmargin", List.of("margin"));
        commandsAndArguments.put("set rmargin", List.of("margin"));
        commandsAndArguments.put("set tmargin", List.of("margin"));
        commandsAndArguments.put("set margins", List.of("left", "right", "bottom", "top"));
        commandsAndArguments.put("set border", List.of("integer", "lineStyle", "lineType", "lineWidth", "colorSpec", "dashType"));
        commandsAndArguments.put("set boxwidth", List.of("width"));
        commandsAndArguments.put("set boxdepth", List.of("depth"));
        commandsAndArguments.put("set colorsequence", null);
        commandsAndArguments.put("set clabel", List.of("format"));
        commandsAndArguments.put("set clip", null);
        commandsAndArguments.put("set cntrlabel", List.of("format", "font", "int"));
        commandsAndArguments.put("set cntrlabel onecolor", null);
        commandsAndArguments.put("set cntrparam", List.of("n", "z1", "z2", "z3", "N", "end"));
        commandsAndArguments.put("set colorbox", List.of("x", "y", "lineStyle"));
        commandsAndArguments.put("set contour", null);
        commandsAndArguments.put("set dashtype", List.of("N", "pattern", "s1", "e1", "s2", "e2", "s3", "e3", "s4", "e4"));
        commandsAndArguments.put("set datafile", List.of());
        commandsAndArguments.put("set decimalsign", List.of("value", "locale"));
        commandsAndArguments.put("set dgrid3d", List.of("rows", "cols", "norm", "dx", "dy"));
        commandsAndArguments.put("set dummy", List.of("dummyVar1", "dummyVar2"));
        commandsAndArguments.put("set encoding", List.of("value"));
        commandsAndArguments.put("set encoding locale", null);
        commandsAndArguments.put("set errorbars", List.of("size"));
        commandsAndArguments.put("set fit", List.of("filename", "value", "epsilon", "epsilonAbs", "command"));
        commandsAndArguments.put("set fontpath", List.of("directory"));
        commandsAndArguments.put("set format", List.of("axes", "formatString"));
        commandsAndArguments.put("set grid", List.of("angle", "linePropertiesMajor", "linePropertiesMinor"));
        commandsAndArguments.put("set hidden3d", List.of("offset", "level", "bitpattern"));
        commandsAndArguments.put("set historysize", List.of("N"));
        commandsAndArguments.put("set history", List.of("N"));
        commandsAndArguments.put("set isosamples", List.of("iso1", "iso2"));
        commandsAndArguments.put("set isosurface", List.of("n"));
        commandsAndArguments.put("set jitter", List.of("yposition", "factor", "limit"));
        commandsAndArguments.put("set key", List.of("position", "sampleLength", "lineSpacing", "widthIncrement",
                "heightIncrement", "text", "face", "size", "colorspec", "style", "type", "width", "maxNoOfColumns", "maxNoOfRows"));
        commandsAndArguments.put("set label", List.of("tag", "labelText", "position", "degrees", "name", "size", "colorspec", "pointstyle", "offset", "boxstyle"));
        commandsAndArguments.put("set linetype", List.of());
        commandsAndArguments.put("set link", List.of("expression1", "expression2"));
        commandsAndArguments.put("set loadpath", List.of("pathlist1", "pathlist2"));
        commandsAndArguments.put("set locale", List.of("locale"));
        commandsAndArguments.put("set logscale", List.of("axes", "base"));
        commandsAndArguments.put("set mapping", null);
        commandsAndArguments.put("set micro", List.of("character"));
        commandsAndArguments.put("set monochrome", List.of("linetypeProperties"));
        commandsAndArguments.put("set mouse", List.of("ms", "xmultiplier", "ymultiplier", "string", "int", "f", "labeloptions"));
        commandsAndArguments.put("set multiplot", List.of("pageTitle", "fontspec", "rows", "cols", "xscale", "yscale",
                "xoff", "yoff", "left", "right", "bottom", "top", "xspacing", "yspacing"));
        commandsAndArguments.put("set mxtics", List.of("freq"));
        commandsAndArguments.put("set nonlinear", List.of("axis"));
        commandsAndArguments.put("set object", List.of("index", "objectType", "objectProperties", "colorspec", "fillStyle", "width", "dashtype"));
        commandsAndArguments.put("set offsets", List.of("left", "right", "top", "bottom"));
        commandsAndArguments.put("set origin", List.of("xOrigin", "yOrigin"));
        commandsAndArguments.put("set output", List.of("filename"));
        commandsAndArguments.put("set overflow", null);
        commandsAndArguments.put("set palette", List.of("gamma", "rgb", "gray1", "color1", "grayN", "colorN", "filename", "R", "G", "B", "startval", "cyclesval", "saturationval", "maxcolors"));
        commandsAndArguments.put("set parametric", null);
        commandsAndArguments.put("set paxis", List.of("axisno", "rangeOptions", "ticOptions", "labelOptions", "radialOffset"));
        commandsAndArguments.put("set pixmap", List.of("index", "filename", "position", "w", "h"));
        commandsAndArguments.put("set pm3d", List.of("position", "steps", "base", "z", "fraction1", "fraction2", "fraction3", "linestyleOptions"));
        commandsAndArguments.put("set pointsize", List.of("multiplier"));
        commandsAndArguments.put("set polar", null);
        commandsAndArguments.put("set print", List.of("filename", "shellCommand", "append"));
        commandsAndArguments.put("set psdir", List.of("directory"));
        commandsAndArguments.put("set rgbmax", List.of("value"));
        commandsAndArguments.put("set samples", List.of("samples1", "samples2"));
        commandsAndArguments.put("set size", List.of("r", "xscale", "yscale"));
        // Uzupełnić set style o dodatkowe dane!
        commandsAndArguments.put("set style function", List.of("style"));
        commandsAndArguments.put("set style data", List.of("style"));
        commandsAndArguments.put("set style arrow", List.of("n", "arrowstyle"));
        commandsAndArguments.put("set style boxplot", List.of("styleOptions"));
        commandsAndArguments.put("set style circle radius", List.of("size"));
        commandsAndArguments.put("set style ellipse", List.of("size"));
        commandsAndArguments.put("set style fill", List.of("fillstyle"));
        commandsAndArguments.put("set style histogram", List.of("styleOptions"));
        commandsAndArguments.put("set style line", List.of("n", "lineStyle"));
        commandsAndArguments.put("set style rectangle", List.of("objectOptions", "linestyle", "fillstyle"));
        commandsAndArguments.put("set style textbox", List.of("n"));
        commandsAndArguments.put("set surface", null);
        commandsAndArguments.put("set table", List.of("outfile", "char"));
        commandsAndArguments.put("set terminal", List.of("terminalType"));
        commandsAndArguments.put("set termoption", List.of("fontname", "fontsize", "scale", "lw"));
        commandsAndArguments.put("set theta", null);
        commandsAndArguments.put("set tics", List.of("ang", "offset", "formatstring", "size", "colorspec", "minor"));
        commandsAndArguments.put("set timestamp", List.of("format", "xoff", "yoff", "fontspec", "colorspec"));
        commandsAndArguments.put("set timefmt", List.of("formatString"));
        commandsAndArguments.put("set title", List.of("titleText", "offset", "font", "size", "colorspec"));
        commandsAndArguments.put("set vgrid", List.of("size"));
        commandsAndArguments.put("set view", List.of("rotx", "rotz", "scale", "scalez", "scale", "angle"));
        commandsAndArguments.put("set vxrange", List.of("vmin", "vmax"));
        commandsAndArguments.put("set vyrange", List.of("vmin", "vmax"));
        commandsAndArguments.put("set vzrange", List.of("vmin", "vmax"));
        commandsAndArguments.put("set wall", List.of("fillstyle", "fillcolor"));
        commandsAndArguments.put("set walls", null);
        commandsAndArguments.put("set xdata time", null);
        commandsAndArguments.put("set ydata time", null);
        commandsAndArguments.put("set zdata time", null);
        commandsAndArguments.put("set x2data time", null);
        commandsAndArguments.put("set y2data time", null);
        commandsAndArguments.put("set z2data time", null);
        commandsAndArguments.put("set xlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set x2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set ylabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set y2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set zlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set cblabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndArguments.put("set xmtics", null);
        commandsAndArguments.put("set x2mtics", null);
        commandsAndArguments.put("set ymtics", null);
        commandsAndArguments.put("set y2mtics", null);
        commandsAndArguments.put("set zmtics", null);
        commandsAndArguments.put("set cbmtics", null);
        commandsAndArguments.put("set xrange", List.of("min", "max"));
        commandsAndArguments.put("set yrange", List.of("min", "max"));
        commandsAndArguments.put("set zrange", List.of("min", "max"));
        commandsAndArguments.put("set x2range", List.of("min", "max"));
        commandsAndArguments.put("set y2range", List.of("min", "max"));
        commandsAndArguments.put("set cbrange", List.of("min", "max"));
        commandsAndArguments.put("set rrrange", List.of("min", "max"));
        commandsAndArguments.put("set trange", List.of("min", "max"));
        commandsAndArguments.put("set urange", List.of("min", "max"));
        commandsAndArguments.put("set vrange", List.of("min", "max"));
        commandsAndArguments.put("xtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("ytics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("ztics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("x2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("y2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("cbtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level",
                "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndArguments.put("set zero", List.of("expression"));
        commandsAndArguments.put("set xzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndArguments.put("set x2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndArguments.put("set yzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndArguments.put("set y2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndArguments.put("set zzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndArguments.put("shell", null);
        commandsAndArguments.put("splot", List.of("ranges", "iteration", "function", "filename", "datablockname", "datafileModifiers", "voxelgridname", "titlespec", "style", "definitions", "function"));
        commandsAndArguments.put("stats", List.of("ranges", "filename", "N", "M", "prefix"));
        commandsAndArguments.put("system", List.of("commandString"));
        commandsAndArguments.put("test", null);
        commandsAndArguments.put("toggle", List.of("plotno", "plottitle"));
        commandsAndArguments.put("undefine", List.of("variables"));
        commandsAndArguments.put("unset", List.of("options"));
        commandsAndArguments.put("update", null);
        commandsAndArguments.put("vclear", List.of("gridname"));
        commandsAndArguments.put("vfill", List.of("file", "x", "y", "z", "radius", "expression"));
        commandsAndArguments.put("while", List.of("expression"));
        commandsAndArguments.put("show bind", null);
        commandsAndArguments.put("show variables", null);
        commandsAndArguments.put("show version", null);

        commandsAndKeywords.put("exit", List.of("message", "status"));
        commandsAndKeywords.put("for", List.of("intvar", "stringvar"));
        commandsAndKeywords.put("fit", List.of("fit {<ranges>} <expression> '<datafile>' {datafile-modifiers} {{unitweights} | {y|xy|z}error | errors <var1>{,<var2>,...}} via '<parameter file>' | <var1>{,<var2>,...}"));
        commandsAndKeywords.put("help", List.of("help {<topic>}"));
        commandsAndKeywords.put("history", List.of("quiet", "append", "?", "!"));
        commandsAndKeywords.put("save", List.of("functions", "variables", "terminal", "set", "fit"));
        commandsAndKeywords.put("set angles", List.of("set angles {degrees | radians}"));
        commandsAndKeywords.put("set arrow", List.of("set arrow {<tag>} from <position> to <position>", "set arrow {<tag>} from <position> rto <position>", "set arrow {<tag>} from <position> length <coord> angle <ang>", "set arrow <tag> arrowstyle | as <arrow_style>", "set arrow <tag> {nohead | head | backhead | heads} {size <headlength>,<headangle>{,<backangle>}} {fixed} {filled | empty | nofilled | noborder} {front | back} {linestyle | ls <line_style>} {linetype | lt <line_type>} {linewidth | lw <line_width>} {linecolor | lc <colorspec>} {dashtype | dt <dashtype>}"));
        commandsAndKeywords.put("set autoscale", List.of("noextend"));
        commandsAndKeywords.put("set bmargin", List.of("at screen"));
        commandsAndKeywords.put("set lmargin", List.of("at screen"));
        commandsAndKeywords.put("set rmargin", List.of("at screen"));
        commandsAndKeywords.put("set tmargin", List.of("at screen"));
        commandsAndKeywords.put("set margins", List.of());
        commandsAndKeywords.put("set border", List.of("front", "back", "behind", "linestyle", "linetype", "linewidth", "linecolor", "dashtype", "polar"));
        commandsAndKeywords.put("set boxwidth", List.of("absolute", "relative"));
        commandsAndKeywords.put("set colorsequence", List.of("default", "classic", "podo"));
        commandsAndKeywords.put("set boxdepth", List.of("depth"));
        commandsAndKeywords.put("set clabel", List.of("format"));
        commandsAndKeywords.put("set clip", List.of("points", "one", "two", "radial"));
        commandsAndKeywords.put("set cntrlabel", List.of("format", "font", "start", "interval", "onecolor"));
        commandsAndKeywords.put("set cntrparam", List.of("linear", "cubicspline", "bspline", "points", "order", "levels", "auto", "discrete", "incremental", "sorted", "unsorted", "firstlinetype"));
        commandsAndKeywords.put("set colorbox", List.of("vertical", "horizontal", "invert", "noinvert", "default", "user", "origin", "size", "front", "back", "noborder", "bdefault", "border"));
        commandsAndKeywords.put("set contour", List.of("base", "surface", "both"));
        commandsAndKeywords.put("set dashtype", List.of());
        commandsAndKeywords.put("set datafile", List.of("missing", "separator", "whitespace", "tab", "comma", "commentschars", "binary"));
        commandsAndKeywords.put("set decimalsign", List.of("value", "locale"));
        commandsAndKeywords.put("set dgrid3d", List.of("splines", "qnorm", "gauss", "cauchy", "exp", "box", "hann"));
        commandsAndKeywords.put("set dummy", List.of());
        commandsAndKeywords.put("set encoding", List.of("locale"));
        commandsAndKeywords.put("set errorbars", List.of("small", "large", "fullwidth", "front", "back"));
        commandsAndKeywords.put("set fit", List.of("nolog", "logfile", "default", "quiet", "noquiet", "results", "brief", "verbose", "errorvariables", "noerrorvariables", "covariancevariables", "nocovariancevariables", "errorscaling", "noerrorscaling", "prescale", "noprescale", "maxiter", "default", "limit", "limit_abs", "start-lambda", "lambda-factor", "script", "v4", "v5"));
        commandsAndKeywords.put("set fontpath", List.of());
        commandsAndKeywords.put("set format", List.of("numeric", "timedate", "geographic"));
        commandsAndKeywords.put("set grid", List.of("xtics", "mxtics", "nomxtics","ytics", "mytics", "nomytics","ztics", "mztics", "nomztics", "x2tics", "mx2tics", "nomx2tics", "y2tics", "my2tics", "nomy2tics", "rtics", "mrtics", "nomrtics", "cbtics", "mcbtics", "nomcbtics", "polar", "layerdefault", "front", "back", "vertical", "novertical"));
        commandsAndKeywords.put("set hidden3d", List.of("defaults", "front", "back", "offset", "nooffset", "trianglepattern", "undefined", "noundefined", "altdiagonal", "noaltdiagonal", "bentover", "nobentover"));
        commandsAndKeywords.put("set historysize", List.of());
        commandsAndKeywords.put("set history", List.of("size", "quiet", "numbers", "full", "trim", "default"));
        commandsAndKeywords.put("set isosamples", List.of());
        commandsAndKeywords.put("set isosurface", List.of("mixed", "triangles", "insidecolor", "noinsidecolor"));
        commandsAndKeywords.put("set jitter", List.of("overlap", "spread", "wrap", "swarm", "square", "vertical"));
        commandsAndKeywords.put("set key", List.of("on", "off", "default", "inside", "outside", "fixed", "lmargin", "rmargin", "tmargin", "bmargin", "at", "left", "right", "center", "top", "bottom", "center", "vertical", "horizontal", "Left", "Right", "enhanced", "noenhanced", "opaque", "noopaque", "reverse", "noreverse", "invert", "noinvert", "samplen", "spacing", "width", "height", "autotitle", "noautotitle", "title", "enhanced", "noenhanced", "font", "textcolor", "box", "nobox", "linetype", "linewidth", "maxcols", "auto", "maxrows"));
        commandsAndKeywords.put("set label", List.of("at", "left", "center", "right", "norotate", "rotate", "by", "font", "noenhanced", "front", "back", "textcolor", "point", "nopoint", "offset", "nobox", "boxed", "hypertext"));
        commandsAndKeywords.put("set linetype", List.of());
        commandsAndKeywords.put("set link", List.of("via", "inverse"));
        commandsAndKeywords.put("set loadpath", List.of());
        commandsAndKeywords.put("set locale", List.of());
        commandsAndKeywords.put("set logscale", List.of());
        commandsAndKeywords.put("set micro", List.of("character"));
        commandsAndKeywords.put("set monochrome", List.of("linetype"));
        commandsAndKeywords.put("set mouse", List.of("doubleclick", "nodoubleclick", "zoomcoordinates", "nozoomcoordinates", "zoomfactors", "noruler", "ruler", "polardistance", "nopolardistance", "format", "mouseformat", "function", "nolabels", "labels", "zoomjump", "nozoomjump", "verbose", "noverbose"));
        commandsAndKeywords.put("set multiplot", List.of("title", "font", "enhanced", "noenhanced", "layout", "rowsfirst", "columnsfirst", "downwards", "upwards", "scale", "offset", "margins", "spacing"));
        commandsAndKeywords.put("set mxtics", List.of("default"));
        commandsAndKeywords.put("set nonlinear", List.of("via", "inverse"));
        commandsAndKeywords.put("set object", List.of("front", "back", "behind", "depthorder", "clip", "noclip", "fillcolor", "fillstyle", "default", "linewidth", "dashtype", "rectangle", "from", "to", "center", "size", "at", "ellipse", "arc", "wedge", "nowedge", "polygon"));
        commandsAndKeywords.put("set offsets", List.of());
        commandsAndKeywords.put("set origin", List.of());
        commandsAndKeywords.put("set output", List.of());
        commandsAndKeywords.put("set palette", List.of("gray", "color", "gamma", "rgbformulae", "defined", "rgbformulae", "defined", "file", "functions", "cubehelix", "cycles", "saturation", "model", "positive", "negative", "nops_allcF", "ps_allcF", "maxcolors"));
        commandsAndKeywords.put("set paxis", List.of("range", "tics", "label", "offset"));
        commandsAndKeywords.put("set pixmap", List.of("index", "filename", "position", "w", "h"));
        commandsAndKeywords.put("set pm3d", List.of("at", "interpolate", "scansautomatic", "scansforward", "scansbackward", "depthorder", "flush", "begin", "center", "end", "ftriangles", "noftriangles", "clip", "clip1in", "clip4in", "clipcb", "noclipcb", "corners2color", "mean", "geomean", "harmean", "rms", "median", "min", "max", "c1", "c2", "c3", "c4", "lighting", "nolighting", "primary", "specular", "spec2", "border", "implicit", "explicit", "map"));
        commandsAndKeywords.put("set pointsize", List.of());
        commandsAndKeywords.put("set print", List.of());
        commandsAndKeywords.put("set psdir", List.of("directory"));
        commandsAndKeywords.put("set rgbmax", List.of("1.0", "255"));
        commandsAndKeywords.put("set samples", List.of());
        commandsAndKeywords.put("set size", List.of("square", "nosquare", "ratio", "noratio"));
        commandsAndKeywords.put("set style function", List.of("style"));
        commandsAndKeywords.put("set style data", List.of("style"));
        commandsAndKeywords.put("set style arrow", List.of("n", "arrowstyle"));
        commandsAndKeywords.put("set style boxplot", List.of("styleOptions"));
        commandsAndKeywords.put("set style circle radius", List.of("clip", "noclip"));
        commandsAndKeywords.put("set style ellipse", List.of("size", "units", "clip", "noclip"));
        commandsAndKeywords.put("set style fill", List.of("fillstyle"));
        commandsAndKeywords.put("set style histogram", List.of("styleOptions"));
        commandsAndKeywords.put("set style line", List.of("n", "lineStyle"));
        commandsAndKeywords.put("set style rectangle", List.of("objectOptions", "linestyle", "fillstyle"));
        commandsAndKeywords.put("set style textbox", List.of("n"));
        commandsAndKeywords.put("set table", List.of("outfile", "char"));
        commandsAndKeywords.put("set terminal", List.of("terminalType"));
        commandsAndKeywords.put("set termoption", List.of("fontname", "fontsize", "scale", "lw"));
        commandsAndKeywords.put("set tics", List.of("ang", "offset", "formatstring", "size", "colorspec", "minor"));
        commandsAndKeywords.put("set timestamp", List.of("format", "xoff", "yoff", "fontspec", "colorspec"));
        commandsAndKeywords.put("set timefmt", List.of("formatString"));
        commandsAndKeywords.put("set title", List.of("titleText", "offset", "font", "size", "colorspec"));
        commandsAndKeywords.put("set vgrid", List.of("size"));
        commandsAndKeywords.put("set view", List.of("rotx", "rotz", "scale", "scalez", "scale", "angle"));
        commandsAndKeywords.put("set vxrange", List.of("vmin", "vmax"));
        commandsAndKeywords.put("set vyrange", List.of("vmin", "vmax"));
        commandsAndKeywords.put("set vzrange", List.of("vmin", "vmax"));
        commandsAndKeywords.put("set wall", List.of("fillstyle", "fillcolor"));
        commandsAndKeywords.put("set xlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set x2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set ylabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set y2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set zlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set cblabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndKeywords.put("set xrange", List.of("min", "max"));
        commandsAndKeywords.put("set yrange", List.of("min", "max"));
        commandsAndKeywords.put("set zrange", List.of("min", "max"));
        commandsAndKeywords.put("set x2range", List.of("min", "max"));
        commandsAndKeywords.put("set y2range", List.of("min", "max"));
        commandsAndKeywords.put("set cbrange", List.of("min", "max"));
        commandsAndKeywords.put("set rrrange", List.of("min", "max"));
        commandsAndKeywords.put("set trange", List.of("min", "max"));
        commandsAndKeywords.put("set urange", List.of("min", "max"));
        commandsAndKeywords.put("set vrange", List.of("min", "max"));
        commandsAndKeywords.put("xtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("ytics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("ztics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("x2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("y2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("cbtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndKeywords.put("set zero", List.of("expression"));
        commandsAndKeywords.put("set xzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndKeywords.put("set x2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndKeywords.put("set yzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndKeywords.put("set y2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndKeywords.put("set zzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndKeywords.put("splot", List.of("ranges", "iteration", "function", "filename", "datablockname", "datafileModifiers", "voxelgridname", "titlespec", "style", "definitions", "function"));
        commandsAndKeywords.put("stats", List.of("ranges", "filename", "N", "M", "prefix"));
        commandsAndKeywords.put("system", List.of("commandString"));
        commandsAndKeywords.put("toggle", List.of("plotno", "plottitle"));
        commandsAndKeywords.put("undefine", List.of("variables"));
        commandsAndKeywords.put("unset", List.of("options"));
        commandsAndKeywords.put("vclear", List.of("gridname"));
        commandsAndKeywords.put("vfill", List.of("file", "x", "y", "z", "radius", "expression"));
        commandsAndKeywords.put("while", List.of("expression"));

        commandsAndTemplates.put("cd", List.of("cd <directory-name>"));
        commandsAndTemplates.put("call", List.of("call <inputfile> <param1> <param2> <param3> <param4> <param5> <param6> <param7> <param8> <param9>"));
        commandsAndTemplates.put("eval", List.of("eval <expression>"));
        commandsAndTemplates.put("exit", List.of("exit", "exit message <error message text>", "exit status <integer error code>"));
        commandsAndTemplates.put("for", List.of("intvar", "stringvar"));
        commandsAndTemplates.put("fit", List.of("fit {<ranges>} <expression> '<datafile>' {datafile-modifiers} {{unitweights} | {y|xy|z}error | errors <var1>{,<var2>,...}} via '<parameter file>' | <var1>{,<var2>,...}"));
        commandsAndTemplates.put("help", List.of("help {<topic>}"));
        commandsAndTemplates.put("history", List.of("history", "history <lastNEntries>", "history quiet <lastNEntries>", "history <file>", "history <file> append", "history <lastNEntries> <expression", "history <lastNEntries> <file>", "history ?<expression>", "history !<expression>"));
        commandsAndTemplates.put("if", List.of("if (<condition>) { <commands>; <commands> }", "if (condition>) { <commands>; <commands> } else { <commands> }", "if (condition>) { <commands>; <commands> } else if { <commands> } else { <commands> }"));
        commandsAndTemplates.put("import", List.of("import func(x[,y,z,...]) from 'sharedobj[:symbol]'"));
        commandsAndTemplates.put("load", List.of("load <input-file>"));
        commandsAndTemplates.put("lower", List.of("lower {plot_window_id}"));
        commandsAndTemplates.put("pause", List.of("pause <time> {'<string>'}", "pause mouse {<endcondition>}{, <endcondition>} {'<string>'}", "pause mouse close"));
        commandsAndTemplates.put("pause mouse", List.of("endCondition", "string"));
        commandsAndTemplates.put("plot", List.of("plot {<ranges>} <plot-element> {, <plot-element>, <plot-element>}", "plot '<file_name>' {binary <binary list>} {{nonuniform} matrix} {index <index list> | index '<name>'} {every <every list>} {skip <number-of-lines>} {using <using list>} {smooth <option>} {bins <options>} {volatile} {noautoscale}", "plot 'DATA' using <XCOL> {:<YCOL>} bins={=<NBINS>} {binrange [<LOW>:<HIGH>]} {binwidth=<width>}", "plot 'file' every {<point_incr>}{:{<block_incr>}{:{<start_point>}{:{<start_block>}{:{<end_point>}{:{<end_block>}}}}}", "plot 'file' index { <m>{:<n>{:<p>}} | '<name>' }"));
        commandsAndTemplates.put("print", List.of("print <expression> {, <expression>, ...}"));
        commandsAndTemplates.put("printerr", List.of("printerr <expression> {, <expression>, ...}"));
        commandsAndTemplates.put("raise", List.of("raise {plot_window_id}"));
        commandsAndTemplates.put("save", List.of("save {functions | variables | terminal | set | fit} '<filename>'"));
        commandsAndArguments.put("set angles", List.of("set angles {degress | radians}"));
        commandsAndTemplates.put("set arrow", List.of("set arrow {<tag>} from <position> to <position>", "set arrow {<tag>} from <position> rto <position>", "set arrow {<tag>} from <position> length <coord> angle <ang>", "set arrow <tag> arrowstyle | as <arrow_style>", "set arrow <tag> {nohead | head | backhead | heads} {size <headlength>,<headangle>{,<backangle>}} {fixed} {filled | empty | nofilled | noborder} {front | back} {linestyle | ls <line_style>} {linetype | lt <line_type>} {linewidth | lw <line_width>} {linecolor | lc <colorspec>} {dashtype | dt <dashtype>}"));
        commandsAndTemplates.put("set autoscale", List.of("set autoscale {<axes>{|min|max|fixmin|fixmax|fix} | fix | keepfix}", "set autoscale noextend", "unset autoscale {<axes>}", "show autoscale"));
        commandsAndTemplates.put("set bmargin", List.of("margin"));
        commandsAndTemplates.put("set lmargin", List.of("margin"));
        commandsAndTemplates.put("set rmargin", List.of("margin"));
        commandsAndTemplates.put("set tmargin", List.of("margin"));
        commandsAndTemplates.put("set margins", List.of("left", "right", "bottom", "top"));
        commandsAndTemplates.put("set border", List.of("set border {<integer>} {front | back | behind} {linestyle | ls <line_style} {linetype | lt <line_type>} {linewidth | lw <line_width> {linecolor | lc <colorspec>} {dashtype | dt <dashtype>} {polar}", "unset border", "show border"));
        commandsAndTemplates.put("set boxwidth", List.of("set boxwidth", "set boxwidth {<width>}", "set boxwidth {<width>} {absolute|relative}"));
        commandsAndTemplates.put("set colorsequence", List.of("set colorsequence {default|classic|podo}"));
        commandsAndTemplates.put("set boxdepth", List.of("depth"));
        commandsAndTemplates.put("set clabel", List.of("format"));
        commandsAndTemplates.put("set clip", List.of("set clip {points|one|two|radial}", "unset clip {points|one|two|radial}"));
        commandsAndTemplates.put("set cntrlabel", List.of("set cntrlabel {format 'format'} {font 'font'}", "set cntrlabel {start <int>} {interval <int>}", "set cntrlabel onecolor"));
        commandsAndTemplates.put("set cntrparam", List.of("set cntrparam { { linear|cubicspline|bspline|points <n>|order <n> | levels { <n> | auto {<n>} | discrete <z1> {,<z2>{,<z3>...}} | incremental <start>, <incr> {,<end>} } {{un}sorted} {firstlinetype N} } }"));
        commandsAndTemplates.put("set colorbox", List.of("set colorbox", "set colorbox { {vertical|horizontal} {{no}invert} {default|user} {origin x, y} {size x, y} {front|back} {noborder | bdefault | border [line style] } }"));
        commandsAndTemplates.put("set contour", List.of("set contour {base|surface|both}", "unset contour", "show contour"));
        commandsAndTemplates.put("set dashtype", List.of("N", "pattern", "s1", "e1", "s2", "e2", "s3", "e3", "s4", "e4"));
        commandsAndTemplates.put("set datafile", List.of());
        commandsAndTemplates.put("set decimalsign", List.of("value", "locale"));
        commandsAndTemplates.put("set dgrid3d", List.of("rows", "cols", "norm", "dx", "dy"));
        commandsAndTemplates.put("set dummy", List.of("dummyVar1", "dummyVar2"));
        commandsAndTemplates.put("set encoding", List.of("value"));
        commandsAndTemplates.put("set errorbars", List.of("size"));
        commandsAndTemplates.put("set fit", List.of("filename", "value", "epsilon", "epsilonAbs", "command"));
        commandsAndTemplates.put("set fontpath", List.of("directory"));
        commandsAndTemplates.put("set format", List.of("axes", "formatString"));
        commandsAndTemplates.put("set grid", List.of("angle", "linePropertiesMajor", "linePropertiesMinor"));
        commandsAndTemplates.put("set hidden3d", List.of("offset", "level", "bitpattern"));
        commandsAndTemplates.put("set historysize", List.of("N"));
        commandsAndTemplates.put("set history", List.of("N"));
        commandsAndTemplates.put("set isosamples", List.of("iso1", "iso2"));
        commandsAndTemplates.put("set isosurface", List.of("n"));
        commandsAndTemplates.put("set jitter", List.of("yposition", "factor", "limit"));
        commandsAndTemplates.put("set key", List.of("position", "sampleLength", "lineSpacing", "widthIncrement", "heightIncrement", "text", "face", "size", "colorspec", "style", "type", "width", "maxNoOfColumns", "maxNoOfRows"));
        commandsAndTemplates.put("set label", List.of("tag", "labelText", "position", "degrees", "name", "size", "colorspec", "pointstyle", "offset", "boxstyle"));
        commandsAndTemplates.put("set linetype", List.of());
        commandsAndTemplates.put("set link", List.of("expression1", "expression2"));
        commandsAndTemplates.put("set loadpath", List.of("pathlist1", "pathlist2"));
        commandsAndTemplates.put("set locale", List.of("locale"));
        commandsAndTemplates.put("set logscale", List.of("axes", "base"));
        commandsAndTemplates.put("set micro", List.of("character"));
        commandsAndTemplates.put("set monochrome", List.of("linetypeProperties"));
        commandsAndTemplates.put("set mouse", List.of("ms", "xmultiplier", "ymultiplier", "string", "int", "f", "labeloptions"));
        commandsAndTemplates.put("set multiplot", List.of("pageTitle", "fontspec", "rows", "cols", "xscale", "yscale", "xoff", "yoff", "left", "right", "bottom", "top", "xspacing", "yspacing"));
        commandsAndTemplates.put("set mxtics", List.of("freq"));
        commandsAndTemplates.put("set nonlinear", List.of("axis"));
        commandsAndTemplates.put("set object", List.of("index", "objectType", "objectProperties", "colorspec", "fillStyle", "width", "dashtype"));
        commandsAndTemplates.put("set offsets", List.of("left", "right", "top", "bottom"));
        commandsAndTemplates.put("set origin", List.of("xOrigin", "yOrigin"));
        commandsAndTemplates.put("set output", List.of("filename"));
        commandsAndTemplates.put("set palette", List.of("gamma", "rgb", "gray1", "color1", "grayN", "colorN", "filename", "R", "G", "B", "startval", "cyclesval", "saturationval", "maxcolors"));
        commandsAndTemplates.put("set paxis", List.of("axisno", "rangeOptions", "ticOptions", "labelOptions", "radialOffset"));
        commandsAndTemplates.put("set pixmap", List.of("index", "filename", "position", "w", "h"));
        commandsAndTemplates.put("set pm3d", List.of("position", "steps", "base", "z", "fraction1", "fraction2", "fraction3", "linestyleOptions"));
        commandsAndTemplates.put("set pointsize", List.of("multiplier"));
        commandsAndTemplates.put("set print", List.of("filename", "shellCommand", "append"));
        commandsAndTemplates.put("set psdir", List.of("directory"));
        commandsAndTemplates.put("set rgbmax", List.of("value"));
        commandsAndTemplates.put("set samples", List.of("samples1", "samples2"));
        commandsAndTemplates.put("set size", List.of("r", "xscale", "yscale"));
        commandsAndTemplates.put("set style function", List.of("style"));
        commandsAndTemplates.put("set style data", List.of("style"));
        commandsAndTemplates.put("set style arrow", List.of("n", "arrowstyle"));
        commandsAndTemplates.put("set style boxplot", List.of("styleOptions"));
        commandsAndTemplates.put("set style circle radius", List.of("size"));
        commandsAndTemplates.put("set style ellipse", List.of("size"));
        commandsAndTemplates.put("set style fill", List.of("fillstyle"));
        commandsAndTemplates.put("set style histogram", List.of("styleOptions"));
        commandsAndTemplates.put("set style line", List.of("n", "lineStyle"));
        commandsAndTemplates.put("set style rectangle", List.of("objectOptions", "linestyle", "fillstyle"));
        commandsAndTemplates.put("set style textbox", List.of("n"));
        commandsAndTemplates.put("set table", List.of("outfile", "char"));
        commandsAndTemplates.put("set terminal", List.of("terminalType"));
        commandsAndTemplates.put("set termoption", List.of("fontname", "fontsize", "scale", "lw"));
        commandsAndTemplates.put("set tics", List.of("ang", "offset", "formatstring", "size", "colorspec", "minor"));
        commandsAndTemplates.put("set timestamp", List.of("format", "xoff", "yoff", "fontspec", "colorspec"));
        commandsAndTemplates.put("set timefmt", List.of("formatString"));
        commandsAndTemplates.put("set title", List.of("titleText", "offset", "font", "size", "colorspec"));
        commandsAndTemplates.put("set vgrid", List.of("size"));
        commandsAndTemplates.put("set view", List.of("rotx", "rotz", "scale", "scalez", "scale", "angle"));
        commandsAndTemplates.put("set vxrange", List.of("vmin", "vmax"));
        commandsAndTemplates.put("set vyrange", List.of("vmin", "vmax"));
        commandsAndTemplates.put("set vzrange", List.of("vmin", "vmax"));
        commandsAndTemplates.put("set wall", List.of("fillstyle", "fillcolor"));
        commandsAndTemplates.put("set xlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set x2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set ylabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set y2label", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set zlabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set cblabel", List.of("label", "offset", "font", "size", "colorspec", "degrees"));
        commandsAndTemplates.put("set xrange", List.of("min", "max"));
        commandsAndTemplates.put("set yrange", List.of("min", "max"));
        commandsAndTemplates.put("set zrange", List.of("min", "max"));
        commandsAndTemplates.put("set x2range", List.of("min", "max"));
        commandsAndTemplates.put("set y2range", List.of("min", "max"));
        commandsAndTemplates.put("set cbrange", List.of("min", "max"));
        commandsAndTemplates.put("set rrrange", List.of("min", "max"));
        commandsAndTemplates.put("set trange", List.of("min", "max"));
        commandsAndTemplates.put("set urange", List.of("min", "max"));
        commandsAndTemplates.put("set vrange", List.of("min", "max"));
        commandsAndTemplates.put("xtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("ytics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("ztics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("x2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("y2tics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("cbtics", List.of("major", "minor", "ang", "offset", "incr", "start", "end", "label", "level", "pos", "formatstring", "fontsize", "colorspec"));
        commandsAndTemplates.put("set zero", List.of("expression"));
        commandsAndTemplates.put("set xzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndTemplates.put("set x2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndTemplates.put("set yzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndTemplates.put("set y2zeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndTemplates.put("set zzeroaxis", List.of("linestyle", "linetype", "linewidth", "colorspec", "dashtype"));
        commandsAndTemplates.put("splot", List.of("ranges", "iteration", "function", "filename", "datablockname", "datafileModifiers", "voxelgridname", "titlespec", "style", "definitions", "function"));
        commandsAndTemplates.put("stats", List.of("ranges", "filename", "N", "M", "prefix"));
        commandsAndTemplates.put("system", List.of("commandString"));
        commandsAndTemplates.put("toggle", List.of("plotno", "plottitle"));
        commandsAndTemplates.put("undefine", List.of("variables"));
        commandsAndTemplates.put("unset", List.of("options"));
        commandsAndTemplates.put("vclear", List.of("gridname"));
        commandsAndTemplates.put("vfill", List.of("file", "x", "y", "z", "radius", "expression"));
        commandsAndTemplates.put("while", List.of("expression"));

        GNUPLOT_COMMANDS_AND_ARGUMENTS = Collections.unmodifiableMap(commandsAndArguments);
        GNUPLOT_COMMANDS_AND_KEYWORDS = Collections.unmodifiableMap(commandsAndKeywords);
        GNUPLOT_COMMANDS_AND_TEMPLATES = Collections.unmodifiableMap(commandsAndTemplates);
    }
}
